version: '3.8'

services:
  server-api:
    build:
      args:
        NODE_ENV: "development"
    container_name: server-api
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
